---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	supervisor(supervisor)
	planner(planner)
	browser_agent(browser_agent)
	cover_letter_agent(cover_letter_agent)
	__end__([<p>__end__</p>]):::last
	__start__ --> supervisor;
	browser_agent --> supervisor;
	cover_letter_agent --> supervisor;
	planner --> supervisor;
	supervisor -. &nbsp;end&nbsp; .-> __end__;
	supervisor -.-> browser_agent;
	supervisor -.-> cover_letter_agent;
	supervisor -.-> planner;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
